flags: {}
extra-package-dbs: []
extra-deps: 
- hsqml-0.3.5.0
- hnn-0.3
- mersenne-random-1.0.0.1
- poker-eval-0.3.1
packages:
- ai
- client
- server
- types
- client-framework
- experiments
resolver: lts-9.11
install-ghc: true
ghc-build: nopie
ghc-options:
    ai: -O0
    types: -O0
    client: "-O0 -threaded"
    server: "-O0 -threaded"
    client-framework: -O0
