flags: {}
extra-package-dbs: []
extra-deps: 
- hsqml-0.3.5.0
packages:
- ai
- client
- server
- types
resolver: lts-9.9
install-ghc: true
ghc-build: nopie
ghc-options:
    $locals: -O0
    client: -threaded
    server: -threaded
