flags: {}
extra-package-dbs: []
extra-deps: 
- hsqml-0.3.5.0
- hnn-0.3
packages:
- ai
- client
- server
- types
resolver: lts-9.11
install-ghc: true
ghc-build: nopie
ghc-options:
    ai: -O0
    types: -O0
    client: "-O0 -threaded"
    server: "-O0 -threaded"
