name: types
version: '0.1.0.0'
author: ZedPea
maintainer: zp+github@zacharypalmer.co.uk
license: BSD3
dependencies:
- base >=4.9 && <=4.11
- lens
library:
    source-dirs: src/lib
    dependencies:
    - network
    - binary
    - transformers
    - uuid-types
