name: server
version: '0.1.0.0'
synopsis: A server hosting a poker game
description: Play texas hold em' poker against other players across the internet
category: Network
author: ZedPea
maintainer: zp+github@zacharypalmer.co.uk
license: BSD3
data-files:
- src/gui/*.qml
- src/gui/assets/*.png
dependencies:
- base >=4.9 && <=4.11
- lens
- random
- transformers
- safe
- uuid-types
- hslogger
- network
- types
- text
- bytestring
- binary
library:
    source-dirs: src/lib
executables:
    server:
        main: Main.hs
        source-dirs: src/exe/server
        dependencies:
        - server
        - hsqml
    shuffletest:
        main: Main.hs
        source-dirs: src/exe/shuffletest
        dependencies:
        - server
        - containers
        - hsqml
        - Chart
        - Chart-cairo
