name: ai
version: '0.1.0.0'
synopsis: An ai to play poker
category: Game
author: ZedPea
maintainer: zp+github@zacharypalmer.co.uk
license: BSD3
dependencies:
- base >=4.9 && <=4.11
- random
- transformers
- types
- lens
- containers
- poker-eval
library:
    source-dirs: src/lib
    dependencies:
    - client-framework
    - binary
    - uuid-types
executables:
  ai-random:
    main: Main.hs
    source-dirs: src/exe/ai-random/
    dependencies:
    - ai
  rule-based-ai:
    main: Main.hs
    source-dirs: src/exe/rule-based-ai/
    dependencies:
    - ai
