name: ai
version: '0.1.0.0'
synopsis: An ai to play poker
category: Game
author: ZedPea
maintainer: zp+github@zacharypalmer.co.uk
license: BSD3
dependencies:
- base >=4.9 && <=4.11
- hnn
- hmatrix
- random
data-files: src/lib/EVs.txt
library:
    source-dirs: src/lib
executables:
  ai-random:
    main: Main.hs
    source-dirs: src/exe/ai-random/
    dependencies:
    - ai
