name: client-framework
version: '0.1.0.0'
synopsis: A framework for connecting to a poker server and exchanging messages
category: Network
author: ZedPea
maintainer: zp+github@zacharypalmer.co.uk
license: BSD3
dependencies:
- base >=4.9 && <=4.11
- types
- lens
- transformers
- network
- binary
- bytestring
- hslogger
- uuid-types
library:
    source-dirs: src
